test_that("simple model 4 recovers expected paths", {
  set.seed(1)
  n <- 300
  x <- rnorm(n)
  m <- 0.8 * x + rnorm(n)
  y <- 0.3 * x + 0.6 * m + rnorm(n)
  d <- data.frame(x, m, y)
  f <- fit_process_diagram(d, x = "x", y = "y", m = "m", model = 4, boot = 0)
  expect_equal(nrow(f$paths), 3)
  expect_true(any(f$paths$from == "x" & f$paths$to == "m"))
  expect_true(any(f$paths$from == "m" & f$paths$to == "y"))
  expect_true(nrow(f$indirect) >= 1)
  expect_true(all(c("boot_se", "boot_llci", "boot_ulci") %in% names(f$indirect)))
  expect_true(all(is.na(f$indirect$boot_se)))
})


test_that("standardization reproduces PROCESS coefficient rounding", {
  set.seed(42)
  n <- 250
  x <- rbinom(n, 1, .5)
  m <- 0.321234 * x + rnorm(n)
  y <- 0.222222 * x + 0.543219 * m + rnorm(n)
  d <- data.frame(x, m, y)

  f <- fit_process_diagram(d, x = "x", y = "y", m = "m", model = 4,
                           standardized = TRUE, boot = 0)
  row <- f$paths[f$paths$from == "m" & f$paths$to == "y", ]
  expected <- as.numeric(sprintf("%.4f", row$estimate)) * sd(d$m) / sd(d$y)
  expect_equal(row$std_estimate, expected, tolerance = 1e-12)
})

test_that("native bootstrap stores a generated seed and standardized intervals", {
  set.seed(123)
  n <- 80
  x <- rbinom(n, 1, .5)
  m <- 0.7 * x + rnorm(n)
  y <- 0.2 * x + 0.5 * m + rnorm(n)
  d <- data.frame(x, m, y)

  f <- fit_process_diagram(
    d, x = "x", y = "y", m = "m", model = 4,
    standardized = TRUE, boot = 25
  )

  expect_true(is.numeric(f$provenance$seed))
  expect_equal(f$provenance$seed_source, "generated by processdiagram")
  expect_true(all(c(
    "std_effect", "std_boot_se", "std_boot_llci", "std_boot_ulci"
  ) %in% names(f$indirect)))
})


test_that("significance stars use conventional thresholds", {
  expect_equal(processdiagram:::.pd_stars(.0009), "***")
  expect_equal(processdiagram:::.pd_stars(.0016), "**")
  expect_equal(processdiagram:::.pd_stars(.02), "*")
  expect_equal(processdiagram:::.pd_stars(.13), "")
})


test_that("binary Y uses logistic regression and disables PROCESS-style standardization", {
  set.seed(2026)
  n <- 300
  x <- rbinom(n, 1, .5)
  m <- 0.6 * x + rnorm(n)
  pr <- plogis(-0.4 + 0.5 * x + 0.7 * m)
  y <- rbinom(n, 1, pr)
  d <- data.frame(x, m, y)

  expect_warning(
    f <- fit_process_diagram(
      d, x = "x", y = "y", m = "m", model = 4,
      standardized = TRUE, boot = 0
    ),
    "does not provide standardized coefficients when Y is dichotomous"
  )

  gy <- glm(y ~ x + m, data = d, family = binomial(link = "logit"))
  py <- f$paths[f$paths$to == "y", , drop = FALSE]

  expect_false(f$standardized)
  expect_true(f$standardized_requested)
  expect_equal(f$outcome_type, "binary")
  expect_true(all(is.na(f$paths$std_estimate)))
  expect_equal(
    py$estimate[py$from == "x"],
    unname(coef(gy)["x"]),
    tolerance = 1e-10
  )
  expect_equal(
    py$estimate[py$from == "m"],
    unname(coef(gy)["m"]),
    tolerance = 1e-10
  )
})
